import 'park_catalog.dart';

enum AnimalKind {
  suricate,
  lion,
  girafe,
  zebre,
  guepard,
  addax,
  atele,
  gibbon,
  paresseux,
  tamarin,
  lemurien,
  saimiri,
  loutre,
  hippopotame,
  capybara,
  vison,
  tortue,
  tapir,
  tigre,
  pandaRoux,
  loup,
  ours,
  glouton,
  cerfSika,
  kulan,
  renne,
  oryx,
  gazelle,
  cerfCochon,
  goral,
  tahr,
  markhor,
  panthereNeiges,
  alpaga,
  urial,
  panthereAmour,
}

extension AnimalKindLabel on AnimalKind {
  String get label => switch (this) {
    AnimalKind.suricate => 'Suricate',
    AnimalKind.lion => 'Lion',
    AnimalKind.girafe => 'Girafe',
    AnimalKind.zebre => 'Zèbre',
    AnimalKind.guepard => 'Guépard',
    AnimalKind.addax => 'Addax',
    AnimalKind.atele => 'Atèle',
    AnimalKind.gibbon => 'Gibbon',
    AnimalKind.paresseux => 'Paresseux',
    AnimalKind.tamarin => 'Tamarin',
    AnimalKind.lemurien => 'Lémurien',
    AnimalKind.saimiri => 'Saïmiri',
    AnimalKind.loutre => 'Loutre',
    AnimalKind.hippopotame => 'Hippopotame pygmée',
    AnimalKind.capybara => 'Capybara',
    AnimalKind.vison => 'Vison',
    AnimalKind.tortue => 'Tortue',
    AnimalKind.tapir => 'Tapir',
    AnimalKind.tigre => 'Tigre',
    AnimalKind.pandaRoux => 'Panda roux',
    AnimalKind.loup => 'Loup',
    AnimalKind.ours => 'Ours',
    AnimalKind.glouton => 'Glouton',
    AnimalKind.cerfSika => 'Cerf sika',
    AnimalKind.kulan => 'Kulan',
    AnimalKind.renne => 'Renne',
    AnimalKind.oryx => 'Oryx',
    AnimalKind.gazelle => 'Gazelle',
    AnimalKind.cerfCochon => 'Cerf cochon',
    AnimalKind.goral => 'Goral',
    AnimalKind.tahr => 'Tahr',
    AnimalKind.markhor => 'Markhor',
    AnimalKind.panthereNeiges => 'Panthère des neiges',
    AnimalKind.alpaga => 'Alpaga',
    AnimalKind.urial => 'Urial',
    AnimalKind.panthereAmour => 'Panthère de l’Amour',
  };

  String get asset =>
      'assets/match3/animals/${name.replaceAll('Roux', '_roux').replaceAll('Sika', '_sika').replaceAll('Cochon', '_cochon').replaceAll('Neiges', '_neiges').replaceAll('Amour', '_amour')}.png'
          .toLowerCase();
}

const animalsByBiome = <LevelBiome, List<AnimalKind>>{
  LevelBiome.savanna: [
    AnimalKind.suricate,
    AnimalKind.lion,
    AnimalKind.girafe,
    AnimalKind.zebre,
    AnimalKind.guepard,
    AnimalKind.addax,
    AnimalKind.gazelle,
    AnimalKind.oryx,
  ],
  LevelBiome.tropical: [
    AnimalKind.atele,
    AnimalKind.gibbon,
    AnimalKind.paresseux,
    AnimalKind.tamarin,
    AnimalKind.lemurien,
    AnimalKind.saimiri,
    AnimalKind.pandaRoux,
    AnimalKind.tapir,
  ],
  LevelBiome.riverside: [
    AnimalKind.loutre,
    AnimalKind.hippopotame,
    AnimalKind.capybara,
    AnimalKind.vison,
    AnimalKind.tortue,
    AnimalKind.tapir,
    AnimalKind.suricate,
    AnimalKind.cerfCochon,
  ],
  LevelBiome.woodland: [
    AnimalKind.tigre,
    AnimalKind.pandaRoux,
    AnimalKind.loup,
    AnimalKind.ours,
    AnimalKind.glouton,
    AnimalKind.cerfSika,
    AnimalKind.renne,
    AnimalKind.panthereAmour,
  ],
  LevelBiome.steppe: [
    AnimalKind.kulan,
    AnimalKind.renne,
    AnimalKind.addax,
    AnimalKind.oryx,
    AnimalKind.gazelle,
    AnimalKind.cerfCochon,
    AnimalKind.goral,
    AnimalKind.tahr,
  ],
  LevelBiome.mountain: [
    AnimalKind.goral,
    AnimalKind.tahr,
    AnimalKind.markhor,
    AnimalKind.panthereNeiges,
    AnimalKind.alpaga,
    AnimalKind.urial,
    AnimalKind.ours,
    AnimalKind.renne,
  ],
  LevelBiome.tundra: [
    AnimalKind.renne,
    AnimalKind.panthereAmour,
    AnimalKind.loup,
    AnimalKind.ours,
    AnimalKind.panthereNeiges,
    AnimalKind.glouton,
    AnimalKind.urial,
    AnimalKind.alpaga,
  ],
};
