import '../../../shared/park_catalog.dart';
import 'models.dart';

List<RepasLevelDefinition> buildRepasCampaign(List<ParkStage> stages) => [
  for (var index = 0; index < stages.length; index++)
    RepasLevelDefinition(
      stage: stages[index],
      rows: _boards[index].rows,
      parPushes: _boards[index].parPushes,
      referenceSolution: _solution(_boards[index].solution),
    ),
];

class _RepasBoard {
  const _RepasBoard(this.parPushes, this.rows, this.solution);

  final int parPushes;
  final List<String> rows;
  final String solution;
}

List<RepasDirection> _solution(String value) => [
  for (final letter in value.split(''))
    switch (letter) {
      'u' => RepasDirection.north,
      'r' => RepasDirection.east,
      'd' => RepasDirection.south,
      'l' => RepasDirection.west,
      _ => throw StateError('Direction inconnue : $letter'),
    },
];

const _boards = [
  _RepasBoard(5, [
    '#######',
    '##.#..#',
    '#..c.t#',
    '#.....#',
    '#t..cs#',
    '#.....#',
    '#######',
  ], 'llulurddluurr'),
  _RepasBoard(4, [
    '#######',
    '#.....#',
    '#..#..#',
    '#...t.#',
    '##.c..#',
    '#.t.cs#',
    '#######',
  ], 'llruulldrdru'),
  _RepasBoard(3, [
    '#######',
    '#.....#',
    '#t#...#',
    '#c#c..#',
    '#st...#',
    '#.....#',
    '#######',
  ], 'udrrruuldrdl'),
  _RepasBoard(5, [
    '#######',
    '#.....#',
    '#...c##',
    '#.ts..#',
    '#.#c..#',
    '#...t.#',
    '#######',
  ], 'duuurdlddrrullulldddrr'),
  _RepasBoard(2, [
    '#######',
    '#.#..t#',
    '#...#c#',
    '#.....#',
    '#..sct#',
    '#.....#',
    '#######',
  ], 'ruru'),
  _RepasBoard(4, [
    '#########',
    '#.......#',
    '#..#....#',
    '#......##',
    '#.......#',
    '##..sct.#',
    '#.......#',
    '#.c..t.##',
    '#########',
  ], 'rdlllldrrr'),
  _RepasBoard(2, [
    '#########',
    '#..#.t.##',
    '#....c..#',
    '#....s..#',
    '#.......#',
    '#.......#',
    '##......#',
    '#.tc...##',
    '#########',
  ], 'udddddll'),
  _RepasBoard(3, [
    '#########',
    '#..#....#',
    '#.......#',
    '#....#..#',
    '#....t..#',
    '#.s..c..#',
    '#.c.....#',
    '#t....###',
    '#########',
  ], 'drdlurrru'),
  _RepasBoard(5, [
    '#########',
    '#....#.##',
    '#..t..t.#',
    '#...#c..#',
    '#.c.....#',
    '#.s.....#',
    '##......#',
    '#.......#',
    '#########',
  ], 'uurdrrudlluurrlullldr'),
  _RepasBoard(5, [
    '#########',
    '#......##',
    '#.......#',
    '#.t#....#',
    '#.......#',
    '#...cs.##',
    '#.#.....#',
    '#.tc....#',
    '#########',
  ], 'ldluruldlurrdddl'),
  _RepasBoard(4, [
    '###########',
    '#.........#',
    '#.......t.#',
    '##......c##',
    '#...#..#..#',
    '#.........#',
    '#.#.......#',
    '#..ct....t#',
    '#...#...c.#',
    '#.......s.#',
    '###########',
  ], 'uruuuuluddlllllllddrrurrrrdr'),
  _RepasBoard(4, [
    '###########',
    '#...#.....#',
    '##........#',
    '#..sc.....#',
    '#.....t...#',
    '#.......ct#',
    '#..C#.....#',
    '#..#.....##',
    '#....#....#',
    '#.........#',
    '###########',
  ], 'rdrrrdrullllururd'),
  _RepasBoard(8, [
    '###########',
    '#........##',
    '#....t....#',
    '#...c.....#',
    '#.....t#..#',
    '#.........#',
    '#....#..#.#',
    '#.#...c...#',
    '#..cs.....#',
    '#t.......##',
    '###########',
  ], 'luuuurulurddddddllrrrrullulllddrrurrruu'),
  _RepasBoard(7, [
    '###########',
    '#......#..#',
    '#........##',
    '#.s.....#.#',
    '#.c.c.....#',
    '#t........#',
    '#....t....#',
    '#..c...#..#',
    '#.........#',
    '#.#t....#.#',
    '###########',
  ], 'durrddlddduurull'),
  _RepasBoard(8, [
    '###########',
    '##........#',
    '#...c.....#',
    '#.##.t..#.#',
    '#.........#',
    '##..c.....#',
    '##t..t....#',
    '#.........#',
    '#.....c...#',
    '#.....s...#',
    '###########',
  ], 'uruluulluuruulldrddldrdddruruuuuuuldlddddl'),
  _RepasBoard(7, [
    '#######',
    '##..#t#',
    '#t....#',
    '#c.#..#',
    '#sc...#',
    '##....#',
    '#######',
  ], 'rrrdruuuddllllu'),
  _RepasBoard(7, [
    '#######',
    '#.s...#',
    '#.cc..#',
    '#..#..#',
    '#..##t#',
    '#.t..##',
    '#######',
  ], 'ddurrurdllldduurrrd'),
  _RepasBoard(7, [
    '#######',
    '#...t.#',
    '#.c####',
    '#.s..##',
    '#...c.#',
    '#t....#',
    '#######',
  ], 'udrddrrulullulurrlddrrdlluld'),
  _RepasBoard(7, [
    '#######',
    '#t#...#',
    '#....##',
    '#.tc.##',
    '#...cs#',
    '#...#.#',
    '#######',
  ], 'lluddlururullrddlluu'),
  _RepasBoard(7, [
    '#######',
    '#..#.t#',
    '#.c.#.#',
    '#..#..#',
    '##.sc.#',
    '#.t...#',
    '#######',
  ], 'rdruuuddllluluurddd'),
  _RepasBoard(10, [
    '#########',
    '#....#..#',
    '###...c.#',
    '#t...##S#',
    '#.....cc#',
    '#....#..#',
    '#......t#',
    '#...#...#',
    '#########',
  ], 'dllluurrllddlrrrrdullldllurulrurrrurd'),
  _RepasBoard(12, [
    '#########',
    '#......##',
    '#c...#..#',
    '#..#....#',
    '#..t.##t#',
    '#.c.....#',
    '#tsc....#',
    '#..##...#',
    '#########',
  ], 'rruuuuulllddrdrrddrrllllluruuldrrrdrrddrullllululdrrrrrdru'),
  _RepasBoard(13, [
    '#########',
    '###t...s#',
    '#.....cc#',
    '#.#.#...#',
    '#...#.c.#',
    '#.......#',
    '##..t...#',
    '#.....#t#',
    '#########',
  ], 'ddlurddluldrrdullduuurrullrrdddddlluuuuul'),
  _RepasBoard(10, [
    '#########',
    '#.......#',
    '#.c..##.#',
    '#....tc.#',
    '#.......#',
    '#...#####',
    '#...sc.t#',
    '#...t.#.#',
    '#########',
  ], 'rrllluuuuuldddddldrruuurrrrul'),
  _RepasBoard(11, [
    '#########',
    '##.....t#',
    '#..#..#.#',
    '#....#..#',
    '#.#...#.#',
    '#.c...t.#',
    '##...c.c#',
    '#...t..s#',
    '#########',
  ], 'uuuuddllululllddrdrrruulldrrrruuudddllllldrurdrdru'),
  _RepasBoard(13, [
    '###########',
    '#.........#',
    '#....#....#',
    '##.t#..##.#',
    '##.cs..c.t#',
    '#...cc...##',
    '##........#',
    '#.t....##.#',
    '#...#..#..#',
    '#..t......#',
    '###########',
  ], 'durrrddllluurdurrrdllllldduurrdrdluullurrdddlld'),
  _RepasBoard(
    13,
    [
      '###########',
      '#....#....#',
      '#.#.......#',
      '#.#.c.cs..#',
      '##...t.c..#',
      '###..###..#',
      '#....#..t.#',
      '#.....#.#.#',
      '#..ct.....#',
      '#t........#',
      '###########',
    ],
    'lulduldrrdrullllddrdddluuuuurdduurrrrdullllddduuurrrrddrdddlllllllulduurrrd',
  ),
  _RepasBoard(
    14,
    [
      '###########',
      '#.........#',
      '###...t...#',
      '#.s#.##...#',
      '#.c.....###',
      '#.......c.#',
      '#....##.#.#',
      '#...#.#...#',
      '#...t.ctc.#',
      '#........t#',
      '###########',
    ],
    'drrrrrdddrduluuullllldrrrrrddrruulrddlluuuuruldddlllllldrdrdrrdrrruuluulllldlddrrrrlllluurdldr',
  ),
  _RepasBoard(
    20,
    [
      '###########',
      '#...##...##',
      '#.c.....t.#',
      '#.c...t.#.#',
      '##....#...#',
      '#..c.....##',
      '##.s......#',
      '##.c.....##',
      '#....##...#',
      '#t...t....#',
      '###########',
    ],
    'duruulddrddlruuuuuululldrrrrrdldddlllddurddluuuuuruulldrrrddddduuuuuurrrllldrddddldldr',
  ),
  _RepasBoard(
    16,
    [
      '###########',
      '#........##',
      '#.#..#..c.#',
      '##........#',
      '#.t...#...#',
      '#....#..#t#',
      '#...t..tc.#',
      '###.......#',
      '##.c..#.c##',
      '#..s......#',
      '###########',
    ],
    'uuruuuuuurrrrdldddddddruluuuuurdrddlrdluruuluurdldldlddlllurrdddrrurulddlluuururuurrdlldldldddrruulullddruluulrddrruldllulu',
  ),
  _RepasBoard(7, [
    '#######',
    '##..###',
    '#.c..##',
    '#.s..t#',
    '#.c#..#',
    '#...t##',
    '#######',
  ], 'dulururdlddldruurlddrluurr'),
  _RepasBoard(7, [
    '#######',
    '#t.#.##',
    '#....##',
    '#.c.cs#',
    '##...##',
    '#.t..##',
    '#######',
  ], 'luldrddlluuruldlurrddrdl'),
  _RepasBoard(8, [
    '#######',
    '#t.cs.#',
    '#.c.#.#',
    '##.##.#',
    '#...###',
    '#....t#',
    '#######',
  ], 'lldddldrrr'),
  _RepasBoard(8, [
    '#######',
    '#s#...#',
    '#c.c..#',
    '#.##..#',
    '#.#...#',
    '#t.##t#',
    '#######',
  ], 'ddurrlldduurrrurddd'),
  _RepasBoard(7, [
    '#######',
    '#...s.#',
    '#.c.c##',
    '#.#..##',
    '#t##..#',
    '#.#t..#',
    '#######',
  ], 'dlluldrrrdduullldurrrddrdl'),
  _RepasBoard(13, [
    '#########',
    '#.#t###.#',
    '#...##t.#',
    '#....cs.#',
    '#...#.c.#',
    '#.#..#..#',
    '##.#.c.t#',
    '#t....c.#',
    '#########',
  ], 'lrrddddllllrrruuudddllurdlllrrrrruuullulrdrrdddllurlluluuudrrdru'),
  _RepasBoard(13, [
    '#########',
    '#.c..t..#',
    '#..cc...#',
    '#..cs##.#',
    '##t...t.#',
    '#....#.##',
    '#.#t..###',
    '#.###...#',
    '#########',
  ], 'lrdrrruuulllduldrdulllurdduurdduurddldrrlld'),
  _RepasBoard(
    13,
    [
      '#########',
      '#.....ts#',
      '#.c.c##c#',
      '#...t#..#',
      '#.#...#.#',
      '##....c.#',
      '###...#t#',
      '#...#t#.#',
      '#########',
    ],
    'ddduuulllllldrurrrrrddddlruuuulllllddrruddrdulullururlddrdrdduululuurrld',
  ),
  _RepasBoard(13, [
    '#########',
    '#..#....#',
    '#..cScc##',
    '#.#..#.##',
    '#...#...#',
    '#t##....#',
    '#.#t....#',
    '#..#.#C.#',
    '#########',
  ], 'lrurrdulldllulddduurrrurrdddduuulrddrddlll'),
  _RepasBoard(13, [
    '#########',
    '#t.s....#',
    '#.ccc.ct#',
    '#...##.##',
    '#t....###',
    '#.....###',
    '##t#....#',
    '##.#....#',
    '#########',
  ], 'dlurrrdlldduurrrlllddrdluuuuldrddlluuddrdurululd'),
  _RepasBoard(
    20,
    [
      '###########',
      '###.......#',
      '#...c#.#c.#',
      '#.c..#t...#',
      '#..t...c#.#',
      '#t#..##...#',
      '##..t#....#',
      '#...##....#',
      '#.c.#..#..#',
      '#.s#..##.t#',
      '###########',
    ],
    'uruuuurrrurdlllddlddllururuurrrrdrddlluruulllddllddruluruuuuurddllururrrrrdulllldllldurrurrrddrdddrurdduuuuuulllllddlllduurrurrrrrrddlrddddduuuuulldlll',
  ),
  _RepasBoard(
    20,
    [
      '###########',
      '##..t##...#',
      '#t.......t#',
      '#.#cc.#.#.#',
      '#......#..#',
      '#c.#.#....#',
      '#...#..#..#',
      '##..#c##.##',
      '#sc..t...t#',
      '#..#.#....#',
      '###########',
    ],
    'rrrluuluurrudllluurrrddlururdllurrrlddlllddrddrrrdrruuuulluluurrurrdddddldddllurruuuuruuulldrllllllurdddlddluuudrrrrrddld',
  ),
  _RepasBoard(
    16,
    [
      '###########',
      '##t.#.....#',
      '#.....#.#.#',
      '#.........#',
      '##..#c#.c.#',
      '#.#.....#t#',
      '#.#.t#.#s.#',
      '#.#.c.#.c##',
      '#t..c.#...#',
      '#.#.#.t...#',
      '###########',
    ],
    'dlddllullrrdrruurduuruuullddlludrruulllrrrrrdddlddrdlluururuuulldrldlllluurrrrrrdullllulldlurddddddlrru',
  ),
  _RepasBoard(
    19,
    [
      '###########',
      '##.c.....t#',
      '#..##C.#..#',
      '#..#.c..#.#',
      '#t....t...#',
      '#.##......#',
      '#.sc.##.#.#',
      '#.#...#####',
      '#c#.....t##',
      '#.........#',
      '###########',
    ],
    'rlluurrrdddldrrdlllluuurrrdrdrluluuulluuurrlldddrrddllludrrruulluuurrrrdddllurdllluuurrrrdduurlddlddlddrdrrlluluuuurruurr',
  ),
  _RepasBoard(
    16,
    [
      '###########',
      '#t#.#....t#',
      '#...ccc..##',
      '#....t#...#',
      '#.#...s##.#',
      '#.t#.#c...#',
      '##c##.....#',
      '#.........#',
      '#...#.#..t#',
      '###....#.##',
      '###########',
    ],
    'drddllururrruuluullldurrrddrddllldrurruuluullldrurrddlurdrddldldllllludrrrururrruulullllddrrdrddruullulluulrrurrdrdrdddduuuulullllllrrrurrrdlllldlllu',
  ),
];
